"""
Static data for all 15 Chennai flood zones.
Sources: GCC, Census 2011, CMDA, TNSDMA risk assessments.
"""

from schemas.models import RiskLevel

CHENNAI_ZONES: list[dict] = [
    {
        "zone_id":           "VEL",
        "name":              "Velachery",
        "latitude":          12.9815,
        "longitude":         80.2180,
        "population":        185000,
        "area_sqkm":         8.4,
        "elevation_m":       6.2,
        "drainage_capacity": 3.1,
        "soil_type":         "Clay — low permeability",
        "static_risk_score": 83.3,
        "risk_class":        RiskLevel.CRITICAL,
        "nearest_stations":  ["Velachery", "Adyar"],
        "rivers_nearby":     ["Adyar"],
    },
    {
        "zone_id":           "ADY",
        "name":              "Adyar Riverbank",
        "latitude":          13.0012,
        "longitude":         80.2565,
        "population":        142000,
        "area_sqkm":         6.7,
        "elevation_m":       4.8,
        "drainage_capacity": 2.8,
        "soil_type":         "Alluvial — flood plain",
        "static_risk_score": 77.0,
        "risk_class":        RiskLevel.CRITICAL,
        "nearest_stations":  ["Adyar", "Nungambakkam"],
        "rivers_nearby":     ["Adyar"],
    },
    {
        "zone_id":           "TAM",
        "name":              "Tambaram",
        "latitude":          12.9249,
        "longitude":         80.1000,
        "population":        221000,
        "area_sqkm":         11.2,
        "elevation_m":       39.0,
        "drainage_capacity": 4.5,
        "soil_type":         "Red loam — moderate drainage",
        "static_risk_score": 62.5,
        "risk_class":        RiskLevel.HIGH,
        "nearest_stations":  ["Tambaram", "Meenambakkam"],
        "rivers_nearby":     ["Adyar upstream"],
    },
    {
        "zone_id":           "MUD",
        "name":              "Mudichur",
        "latitude":          12.8964,
        "longitude":         80.0725,
        "population":        98000,
        "area_sqkm":         9.8,
        "elevation_m":       32.0,
        "drainage_capacity": 4.0,
        "soil_type":         "Black cotton — shrink-swell",
        "static_risk_score": 60.1,
        "risk_class":        RiskLevel.HIGH,
        "nearest_stations":  ["Tambaram"],
        "rivers_nearby":     [],
    },
    {
        "zone_id":           "SAI",
        "name":              "Saidapet",
        "latitude":          13.0209,
        "longitude":         80.2214,
        "population":        167000,
        "area_sqkm":         5.9,
        "elevation_m":       8.1,
        "drainage_capacity": 3.5,
        "soil_type":         "Sandy clay loam",
        "static_risk_score": 64.8,
        "risk_class":        RiskLevel.HIGH,
        "nearest_stations":  ["Nungambakkam", "Adyar"],
        "rivers_nearby":     ["Adyar", "Buckingham Canal"],
    },
    {
        "zone_id":           "KOL",
        "name":              "Kolathur",
        "latitude":          13.1175,
        "longitude":         80.2147,
        "population":        193000,
        "area_sqkm":         7.3,
        "elevation_m":       11.5,
        "drainage_capacity": 3.8,
        "soil_type":         "Clay — low drainage",
        "static_risk_score": 61.4,
        "risk_class":        RiskLevel.HIGH,
        "nearest_stations":  ["Kolathur"],
        "rivers_nearby":     ["Kosasthalaiyar"],
    },
    {
        "zone_id":           "PER",
        "name":              "Perambur",
        "latitude":          13.1163,
        "longitude":         80.2334,
        "population":        241000,
        "area_sqkm":         8.6,
        "elevation_m":       14.2,
        "drainage_capacity": 3.3,
        "soil_type":         "Clay loam",
        "static_risk_score": 58.7,
        "risk_class":        RiskLevel.HIGH,
        "nearest_stations":  ["Kolathur"],
        "rivers_nearby":     ["Cooum"],
    },
    {
        "zone_id":           "TNG",
        "name":              "T. Nagar",
        "latitude":          13.0400,
        "longitude":         80.2337,
        "population":        308000,
        "area_sqkm":         5.2,
        "elevation_m":       12.3,
        "drainage_capacity": 4.2,
        "soil_type":         "Sandy loam",
        "static_risk_score": 55.2,
        "risk_class":        RiskLevel.HIGH,
        "nearest_stations":  ["Nungambakkam"],
        "rivers_nearby":     ["Cooum", "Buckingham Canal"],
    },
    {
        "zone_id":           "SHO",
        "name":              "Sholinganallur",
        "latitude":          12.9010,
        "longitude":         80.2279,
        "population":        124000,
        "area_sqkm":         10.1,
        "elevation_m":       7.6,
        "drainage_capacity": 3.0,
        "soil_type":         "Sandy clay — coastal",
        "static_risk_score": 59.9,
        "risk_class":        RiskLevel.HIGH,
        "nearest_stations":  ["Sholinganallur", "Velachery"],
        "rivers_nearby":     ["Buckingham Canal"],
    },
    {
        "zone_id":           "MAR",
        "name":              "Marina North",
        "latitude":          13.0573,
        "longitude":         80.2825,
        "population":        118000,
        "area_sqkm":         4.5,
        "elevation_m":       3.5,
        "drainage_capacity": 2.5,
        "soil_type":         "Coastal sand — high permeability but storm surge risk",
        "static_risk_score": 57.3,
        "risk_class":        RiskLevel.HIGH,
        "nearest_stations":  ["Nungambakkam"],
        "rivers_nearby":     ["Bay of Bengal coastal"],
    },
    {
        "zone_id":           "POR",
        "name":              "Porur",
        "latitude":          13.0368,
        "longitude":         80.1572,
        "population":        156000,
        "area_sqkm":         9.4,
        "elevation_m":       22.0,
        "drainage_capacity": 5.5,
        "soil_type":         "Red sandy loam",
        "static_risk_score": 44.6,
        "risk_class":        RiskLevel.MEDIUM,
        "nearest_stations":  ["Porur"],
        "rivers_nearby":     ["Adyar upstream", "Chembarambakkam"],
    },
    {
        "zone_id":           "ANN",
        "name":              "Anna Nagar",
        "latitude":          13.0850,
        "longitude":         80.2101,
        "population":        278000,
        "area_sqkm":         6.8,
        "elevation_m":       17.4,
        "drainage_capacity": 5.0,
        "soil_type":         "Sandy loam",
        "static_risk_score": 41.2,
        "risk_class":        RiskLevel.MEDIUM,
        "nearest_stations":  ["Nungambakkam"],
        "rivers_nearby":     ["Cooum"],
    },
    {
        "zone_id":           "AMB",
        "name":              "Ambattur",
        "latitude":          13.1143,
        "longitude":         80.1548,
        "population":        203000,
        "area_sqkm":         12.3,
        "elevation_m":       19.8,
        "drainage_capacity": 5.8,
        "soil_type":         "Red loam",
        "static_risk_score": 38.5,
        "risk_class":        RiskLevel.MEDIUM,
        "nearest_stations":  ["Porur", "Kolathur"],
        "rivers_nearby":     ["Cooum upstream"],
    },
    {
        "zone_id":           "ALW",
        "name":              "Alwarpet",
        "latitude":          13.0350,
        "longitude":         80.2550,
        "population":        89000,
        "area_sqkm":         3.8,
        "elevation_m":       10.5,
        "drainage_capacity": 6.2,
        "soil_type":         "Clay loam — moderate",
        "static_risk_score": 36.8,
        "risk_class":        RiskLevel.MEDIUM,
        "nearest_stations":  ["Nungambakkam", "Adyar"],
        "rivers_nearby":     ["Adyar"],
    },
    {
        "zone_id":           "NUN",
        "name":              "Nungambakkam",
        "latitude":          13.0569,
        "longitude":         80.2425,
        "population":        134000,
        "area_sqkm":         5.1,
        "elevation_m":       23.6,
        "drainage_capacity": 7.0,
        "soil_type":         "Sandy — good drainage",
        "static_risk_score": 22.4,
        "risk_class":        RiskLevel.LOW,
        "nearest_stations":  ["Nungambakkam"],
        "rivers_nearby":     [],
    },
]

# Zone lookup by ID
ZONE_MAP: dict[str, dict] = {z["zone_id"]: z for z in CHENNAI_ZONES}

# Historical flood events
HISTORICAL_EVENTS = [
    {
        "year": 2015, "month": "December",
        "peak_rainfall_mm": 490, "deaths": 94, "displaced": 500000,
        "severity": "severe",
        "description": "Worst flood in 100 years. Adyar breached banks. City paralysed for 2 weeks.",
    },
    {
        "year": 2021, "month": "November",
        "peak_rainfall_mm": 280, "deaths": 12, "displaced": 125000,
        "severity": "moderate",
        "description": "Northeast monsoon surge. Velachery and Saidapet worst affected.",
    },
    {
        "year": 2023, "month": "December",
        "peak_rainfall_mm": 255, "deaths": 9, "displaced": 80000,
        "severity": "moderate",
        "description": "Cyclone Michaung landfall. Coastal zones and Adyar basin inundated.",
    },
    {
        "year": 2005, "month": "October",
        "peak_rainfall_mm": 210, "deaths": 6, "displaced": 45000,
        "severity": "moderate",
        "description": "Early northeast monsoon surge.",
    },
    {
        "year": 2008, "month": "November",
        "peak_rainfall_mm": 185, "deaths": 4, "displaced": 32000,
        "severity": "minor",
        "description": "Localised flooding in low-lying zones.",
    },
]